### ISSUE TITLE
Spongeless Version

### ISSUE THREAD

**Issue by Renari** [xPXpanD/EvenMorePixelmonCommands#1]
Sponge Forge causes issues with many mods and I'd like to use it without it. If the commands are all registered as op only commands something like Forge Essentials can be used for permissions instead of Sponge.

**Comment by xPXpanD** [comment]
Thanks for the post. Changing to pure Forge would be a big undertaking -- Sponge is integral to the current mod working, with parts of it being used throughout. I would at some point like to do this, but can't give an ETA (or even whether I'd actually be able to do it without losing functionality) there. Stay tuned, though!

(closing this ticket)
